---

- name: Change the CD-ROM drive letter
  ansible.windows.win_shell: |
    $cd = $NULL
    $cd = Get-WMIObject -Class Win32_CDROMDrive -ComputerName $env:COMPUTERNAME -ErrorAction Stop
    if ($cd.Drive -eq "{{ windows_storage_dvd['from'] }}:")
    {
       Write-Output "Changing CD Drive letter from '{{ windows_storage_dvd['from'] }}' to '{{ windows_storage_dvd['to'] }}'"
       Set-WmiInstance -InputObject ( Get-WmiObject -Class Win32_volume -Filter "DriveLetter = '{{ windows_storage_dvd['from'] }}:'" ) -Arguments @{DriveLetter='{{ windows_storage_dvd['to'] | lower }}:'}
       exit 1
    } else {
       exit 0
    }
  register: __cdrom_drive
  changed_when: __cdrom_drive.rc == 1
  failed_when: __cdrom_drive.rc > 1
  when: windows_storage_dvd is defined
